In [1]:
import numpy as np

print("NumPy version:", np.__version__)
print("W1 D1 - NumPy Basics")

NumPy version: 2.5.2
W1 D1 - NumPy Basics


In [2]:
# 1D Array
array_1d = np.array([10, 20, 30, 40, 50])

# 2D Array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)

print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D Array:
[10 20 30 40 50]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [3]:
# Broadcasting
numbers = np.array([10, 20, 30, 40, 50])
result = numbers + 5

print("Original:", numbers)
print("After adding 5:", result)

# Vectorised operations
values = np.array([1, 2, 3, 4, 5])

squared = values ** 2
doubled = values * 2

print("\nOriginal values:", values)
print("Squared:", squared)
print("Doubled:", doubled)

Original: [10 20 30 40 50]
After adding 5: [15 25 35 45 55]

Original values: [1 2 3 4 5]
Squared: [ 1  4  9 16 25]
Doubled: [ 2  4  6  8 10]


In [4]:
# Matrix multiplication

matrix_a = np.array([
    [1, 2],
    [3, 4]
])

matrix_b = np.array([
    [5, 6],
    [7, 8]
])

matrix_result = matrix_a @ matrix_b

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nMatrix A × B:")
print(matrix_result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix A × B:
[[19 22]
 [43 50]]


In [5]:
import numpy as np

data = np.genfromtxt(
    "../data/student_data.csv",
    delimiter=",",
    skip_header=1
)

print("Dataset:")
print(data)

print("\nShape:", data.shape)

FileNotFoundError: ../data/student_data.csv not found.

In [6]:
from pathlib import Path
import numpy as np

project_root = Path.cwd().parent
csv_path = project_root / "data" / "dataset.csv"

data = np.genfromtxt(
    csv_path,
    delimiter=",",
    skip_header=1
)

print("Dataset:")
print(data)

print("\nShape:", data.shape)

Dataset:
[[ 2.  6. 55.]
 [ 3.  7. 62.]
 [ 4.  6. 68.]
 [ 5.  8. 75.]
 [ 6.  7. 80.]
 [ 7.  8. 85.]
 [ 8.  7. 89.]
 [ 9.  8. 94.]
 [10.  9. 97.]
 [ 4.  5. 65.]]

Shape: (10, 3)


In [7]:
# Separate the columns
hours_studied = data[:, 0]
sleep_hours = data[:, 1]
exam_score = data[:, 2]

# Mean
mean_score = np.mean(exam_score)

# Standard deviation
std_score = np.std(exam_score)

# Correlation
correlation = np.corrcoef(hours_studied, exam_score)[0, 1]

print("Mean exam score:", mean_score)
print("Standard deviation:", std_score)
print("Correlation (study hours vs exam score):", correlation)


Mean exam score: 77.0
Standard deviation: 13.579396157414365
Correlation (study hours vs exam score): 0.9928185908213107
